SET(CMAKE_Go_COMPILER "/usr/local/bin/go")
SET(CMAKE_Go_COMPILER_LOADED 1)

SET(CMAKE_Go_SOURCE_FILE_EXTENSIONS go)
SET(CMAKE_Go_LINKER_PREFERENCE 40)
SET(CMAKE_Go_OUTPUT_EXTENSION .o)
SET(CMAKE_Go_OUTPUT_EXTENSION_REPLACE 1)
SET(CMAKE_Go_COMPILER_ENV_VAR "GO_COMPILER")
